# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  core-web-api-service:
    image: core.web.api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5001
      - 5002
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://0.0.0.0:5001;http://0.0.0.0:5002
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
