# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  core-web-api-service:
    image: core.web.api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80
